# Generated by Django 4.1 on 2022-09-20 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_salesorder_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
