# Generated by Django 4.1 on 2022-12-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0010_alter_salesorder_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="salesorder", name="done",),
    ]
