# Generated by Django 4.1 on 2022-08-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0002_remove_deliverynotematerial_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.product",
            ),
        ),
    ]
