# Generated by Django 4.1 on 2022-08-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0005_deliverynotematerial_supplier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailMrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                ("quantity_production", models.PositiveIntegerField()),
                (
                    "mrp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.materialrequirementplanning",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="ppic.product",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
