# Generated by Django 4.1 on 2022-08-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0009_materialorder_done_productorder_done_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseProductfix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "process",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.process",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="ppic.product",
                    ),
                ),
                (
                    "warehouse_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.warehousetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("warehouse_type", "product")},
            },
        ),
        
    ]
