# Generated by Django 4.1 on 2022-08-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0010_warehouseproductfix_and_more"),
        ("ppic", "0011_rename_warehouseproductfix_warehouseproduct"),
    ]

    operations = []
