# Generated by Django 4.1 on 2022-08-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0012_merge_20220827_2141"),
    ]

    operations = [
        migrations.DeleteModel(name="WarehouseWip",),
    ]
