# Generated by Django 4.1 on 2022-08-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0015_alter_warehouseproduct_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="warehouseproduct", unique_together={("warehouse_type", "process")},
        ),
    ]
