# Generated by Django 4.1 on 2022-09-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0019_remove_requirementmaterial_conversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material", name="length", field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="thickness",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="material", name="weight", field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="material", name="width", field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="product", name="weight", field=models.FloatField(blank=True),
        ),
        migrations.CreateModel(
            name="ConversionUom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uom_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_inputs",
                        to="ppic.unitofmaterial",
                    ),
                ),
                (
                    "uom_output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_outputs",
                        to="ppic.unitofmaterial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversionMaterialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_input", models.PositiveIntegerField()),
                ("quantity_output", models.PositiveIntegerField()),
                (
                    "material_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_material_inputs",
                        to="ppic.material",
                    ),
                ),
                (
                    "material_output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_material_outputs",
                        to="ppic.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasedConversionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_input", models.PositiveIntegerField()),
                ("quantity_output", models.PositiveIntegerField()),
                (
                    "material_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="based_material_inputs",
                        to="ppic.material",
                    ),
                ),
                (
                    "material_output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="based_material_outputs",
                        to="ppic.material",
                    ),
                ),
            ],
        ),
    ]
