# Generated by Django 4.1 on 2022-09-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0020_alter_material_length_alter_material_thickness_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="basedconversionmaterial",
            unique_together={("material_input", "material_output")},
        ),
        migrations.AlterUniqueTogether(
            name="conversionuom", unique_together={("uom_input", "uom_output")},
        ),
    ]
