# Generated by Django 4.1 on 2022-10-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0029_productdeliversubcont_process"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequirementProductsubcont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="ppic.product",
                    ),
                ),
                (
                    "product_subcont",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.productdeliversubcont",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="RequirementMaterialSubcont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="ppic.material",
                    ),
                ),
                (
                    "product_subcont",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.productdeliversubcont",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
