# Generated by Django 4.1 on 2022-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0035_alter_deliverynotematerial_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversionmaterialreport",
            name="quantity_input",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="materialproductionreport",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="warehousematerial",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(name="WarehouseScrapMaterial",),
    ]
