# Generated by Django 4.1 on 2022-12-19 15:10

from django.db import migrations, models
import ppic.models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0037_alter_requirementmaterialsubcont_quantity"),
    ]

    operations = [
        migrations.RemoveField(model_name="productdelivercustomer", name="paid",),
        migrations.AddField(
            model_name="material",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="materialorder",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productdelivercustomer",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productdeliversubcont",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productorder",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
    ]
