# Generated by Django 4.1 on 2022-12-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0039_alter_materialorder_price_alter_productorder_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="thickness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="width",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdelivercustomer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productdeliversubcont",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
