# Generated by Django 4.1 on 2022-12-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0043_remove_materialorder_done_remove_productorder_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="berat_jenis",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialorder",
            name="to_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ppic.product",
            ),
        ),
    ]
