# Generated by Django 4.1 on 2022-08-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchaseordermaterial", name="supplier",),
        migrations.AddField(
            model_name="purchaseordermaterial",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
            preserve_default=False,
        ),
    ]
