# Generated by Django 4.1 on 2022-08-19 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0004_alter_purchaseordermaterial_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseordermaterial",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
