# Generated by Django 4.1 on 2022-12-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0009_purchaseordermaterial_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseordermaterial",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
