# Generated by Django 4.1 on 2022-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_salesorder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
