# Generated by Django 4.1 on 2022-12-19 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_alter_customer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date", models.DateField(default=datetime.date.today)),
                ("discount", models.PositiveBigIntegerField(default=0)),
                ("tax", models.PositiveSmallIntegerField(default=10)),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketing.salesorder",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
