# Generated by Django 4.1 on 2022-12-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0008_salesorder_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice", name="done", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
