# Generated by Django 4.1 on 2022-08-17 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_remove_purchaseordermaterial_supplier_and_more"),
        ("marketing", "0002_alter_salesorder_customer"),
        ("ppic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="deliverynotematerial", name="supplier",),
        migrations.RemoveField(model_name="deliverynotesubcont", name="supplier",),
        migrations.RemoveField(model_name="material", name="supplier",),
        migrations.AddField(
            model_name="deliverynotesubcont",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliverynotecustomer",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="deliverynotecustomer",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="marketing.customer",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynotematerial",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="deliverynotesubcont",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="materialorder",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.material",
            ),
        ),
        migrations.AlterField(
            model_name="materialrequirementplanning",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.material",
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="marketing.customer",
            ),
        ),
        migrations.AlterField(
            model_name="productdeliversubcont",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.product",
            ),
        ),
        migrations.AlterField(
            model_name="requirementmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.material",
            ),
        ),
        migrations.AlterField(
            model_name="requirementproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.product",
            ),
        ),
        migrations.AlterField(
            model_name="warehousematerial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.material",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="ppic.product",
            ),
        ),
    ]
