# Generated by Django 4.1 on 2022-08-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0004_alter_purchaseordermaterial_supplier"),
        ("ppic", "0004_rename_product_deliverynotesubcont_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynotematerial",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynotecustomer",
            name="note",
            field=models.TextField(default="Delivery Note"),
        ),
        migrations.AlterField(
            model_name="deliverynotematerial",
            name="note",
            field=models.TextField(default="Delivery Note"),
        ),
        migrations.AlterField(
            model_name="deliverynotesubcont",
            name="note",
            field=models.TextField(default="Delivery Note"),
        ),
        migrations.AlterField(
            model_name="deliverynotesubcont",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
        ),
    ]
