# Generated by Django 4.1 on 2022-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0008_alter_process_options_productproductionreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialorder",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productorder",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="materialorder",
            name="arrived",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productionreport",
            name="quantity_not_good",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="delivered",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
