# Generated by Django 4.1 on 2022-08-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0013_delete_warehousewip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseproduct",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ppic.process"
            ),
        ),
    ]
