# Generated by Django 4.1 on 2022-08-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0016_alter_warehouseproduct_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="warehousematerial", unique_together=set(),
        ),
        migrations.RemoveField(model_name="warehousematerial", name="warehouse_type",),
    ]
