# Generated by Django 4.1 on 2022-08-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0017_alter_warehousematerial_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehousematerial",
            name="material",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="ppic.material"
            ),
        ),
        migrations.AlterField(
            model_name="warehousematerial",
            name="quantity",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="warehouseproduct",
            name="quantity",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
