# Generated by Django 4.1 on 2022-08-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0018_alter_warehousematerial_material_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="requirementmaterial", name="conversion",),
        migrations.RemoveField(model_name="requirementproduct", name="conversion",),
        migrations.AddField(
            model_name="requirementmaterial",
            name="input",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="requirementmaterial",
            name="output",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="requirementproduct",
            name="input",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="requirementproduct",
            name="output",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="WarehouseScrapMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ppic.material"
                    ),
                ),
            ],
        ),
    ]
