# Generated by Django 4.1 on 2022-10-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0024_deliverynotecustomer_date_deliverynotematerial_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledproductdelivery", name="product_delivery",
        ),
        migrations.RemoveField(model_name="scheduledproductdelivery", name="schedule",),
        migrations.AddField(
            model_name="materialreceipt",
            name="schedules",
            field=models.ManyToManyField(blank=True, to="ppic.materialreceiptschedule"),
        ),
        migrations.AddField(
            model_name="productdelivercustomer",
            name="schedules",
            field=models.ManyToManyField(blank=True, to="ppic.deliveryschedule"),
        ),
        migrations.DeleteModel(name="ScheduledMaterialArrival",),
        migrations.DeleteModel(name="ScheduledProductDelivery",),
    ]
