# Generated by Django 4.1 on 2022-10-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0025_remove_scheduledproductdelivery_product_delivery_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="productdelivercustomer", name="schedules",),
        migrations.AddField(
            model_name="productdelivercustomer",
            name="schedules",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ppic.deliveryschedule",
            ),
        ),
    ]
