# Generated by Django 4.1 on 2022-10-29 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0006_purchaseordermaterial_done"),
        ("ppic", "0027_remove_materialreceipt_schedules_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptNoteSubcont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(default="Delivery Note")),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)ss",
                        to="purchasing.supplier",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ReceiptSubcontSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                ("date", models.DateField()),
                ("fulfilled_quantity", models.PositiveIntegerField(default=0)),
                (
                    "product_subcont",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.productdeliversubcont",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="productionreport",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name="SubcontReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "product_subcont",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.productdeliversubcont",
                    ),
                ),
                (
                    "receipt_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ppic.receiptnotesubcont",
                    ),
                ),
                (
                    "schedules",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ppic.receiptsubcontschedule",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
