# Generated by Django 4.1 on 2022-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0030_requirementproductsubcont_requirementmaterialsubcont"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontreceipt",
            name="quantity_not_good",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
