# Generated by Django 4.1 on 2022-10-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0031_subcontreceipt_quantity_not_good"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="price",),
        migrations.AlterUniqueTogether(
            name="process", unique_together={("order", "product")},
        ),
    ]
