# Generated by Django 4.1 on 2022-11-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0032_remove_product_price_alter_process_unique_together"),
    ]

    operations = [
        migrations.RemoveField(model_name="detailmrp", name="quantity_production",),
    ]
