# Generated by Django 4.1 on 2022-11-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0033_remove_detailmrp_quantity_production"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailmrp",
            name="quantity_production",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
