# Generated by Django 4.1 on 2022-11-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0007_purchaseordermaterial_date_and_more"),
        ("ppic", "0034_detailmrp_quantity_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynotematerial",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynotesubcont",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="receiptnotesubcont",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="purchasing.supplier",
            ),
        ),
    ]
