# Generated by Django 4.1 on 2022-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0036_alter_conversionmaterialreport_quantity_input_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirementmaterialsubcont",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
