# Generated by Django 4.1 on 2022-12-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0038_remove_productdelivercustomer_paid_material_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialorder",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
