# Generated by Django 4.1 on 2022-12-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0040_material_density_alter_material_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="material", name="density",),
    ]
