# Generated by Django 4.1 on 2022-12-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0041_remove_material_density"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdelivercustomer",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="productdeliversubcont",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
