# Generated by Django 4.1 on 2022-12-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppic", "0042_alter_productdelivercustomer_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="materialorder", name="done",),
        migrations.RemoveField(model_name="productorder", name="done",),
    ]
