# Generated by Django 4.1 on 2022-11-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_rename_type_name_activity_name_useractivity_created"),
    ]

    operations = [
        migrations.RemoveField(model_name="useractivity", name="activity",),
        migrations.RemoveField(model_name="useractivity", name="user",),
        migrations.DeleteModel(name="Activity",),
        migrations.DeleteModel(name="UserActivity",),
    ]
