# Generated by Django 4.1 on 2022-08-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_remove_purchaseordermaterial_supplier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseordermaterial", old_name="product", new_name="supplier",
        ),
    ]
