# Generated by Django 4.1 on 2022-12-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0008_purchaseordermaterial_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseordermaterial",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
