# Generated by Django 4.1 on 2022-12-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0010_purchaseordermaterial_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseordermaterial",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
