# Generated by Django 4.1 on 2022-08-19 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity", old_name="type_name", new_name="name",
        ),
        migrations.AddField(
            model_name="useractivity",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
